### ISSUE TITLE
Fix Provider "gps" unknown.

### ISSUE THREAD

**Issue by emcorrales** [EmmanuelCorrales/android-location-spoofer#4]
Device crashing.
**Replication**: Restart device then start the app. Spoof with the form. Crash occurs.
**Devices**: Sony E5603 Marshmallow, Huawei Nexus 6P, Nexus 6P emulator
**Android Version**: 6.0, 7.1.1

Fatal Exception: java.lang.IllegalArgumentException: Provider "gps" unknown
       at android.os.Parcel.readException(Parcel.java:1688)
       at android.os.Parcel.readException(Parcel.java:1637)
       at android.location.ILocationManager$Stub$Proxy.setTestProviderLocation(ILocationManager.java:1160)
       at android.location.LocationManager.setTestProviderLocation(LocationManager.java:1291)
       at com.emmanuelcorrales.locationspoofer.activities.MainActivity.mockLocation(MainActivity.java:202)
       at com.emmanuelcorrales.locationspoofer.activities.MainActivity.mockLocation(MainActivity.java:190)
       at com.emmanuelcorrales.locationspoofer.activities.MainActivity.access$000(MainActivity.java:34)
       at com.emmanuelcorrales.locationspoofer.activities.MainActivity$1.onClick(MainActivity.java:121)
       at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:157)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6119)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by emcorrales** [comment]
Fixed. 180b4a79229902595dea2ff40934d2e9aa28db05
